model = "gpt-5.2-codex"
model_reasoning_effort = "high"
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]

[features]
web_search_request = true
unified_exec = true
shell_snapshot = true

[notice]
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.deepwiki]
url = "https://mcp.deepwiki.com/mcp"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "ide-assistant", "--project", "/Users/rei"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]
